# Generated by Django 3.2.8 on 2022-01-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20220122_1514'),
        ('ordersapp', '0002_rename_orderitem_orderitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
